version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestMapsetsProject
  gitServerName: test
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
